repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.5
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: black-check
        name: black-check
        entry: uv run --with black black --check .
        language: system
        pass_filenames: false
      - id: flake8-check
        name: flake8-check
        entry: uv run --with flake8 flake8 .
        language: system
        pass_filenames: false
      - id: mypy-check
        name: mypy-check
        entry: uv run mypy server controller model campus_wave
        language: system
        pass_filenames: false
